# Generated by Django 4.2.16 on 2024-12-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("mission", models.TextField()),
                ("vision", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
